#define PID_fPR_0
#define PID_Ts_NOT0
#define PID_fSR_0
#define PID_Ki_NOT0
#define PID_cICM_0
#define PID_cDorR_0
#define PID_Kd_0
#define PID_cSelect_0
#define PID_cOCM_0
#define PID_fMR_NOT0
#define PID_cFHorNH_0
#define PID_cFSorNS_0
#define PID_cCtrlMode_0
#define OPTIMISE_QUEUE
#define OPTIMISE_MATRIX
